version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint:
    docker:
      - image: cimg/node:16.18.0
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:16.18.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test

workflows:
  version: 2.1
  lint-and-test:
    jobs:
      - lint
      - test
